version: "3.8"

services:
  adminer:
    restart: always
    image: adminer:latest
    ports:
      - 3000:8080

  postgres:
    restart: always
    image: postgres:14.5
    environment:
      POSTGRES_USER: "task_user"
      POSTGRES_PASSWORD: "task_password"
      POSTGRES_DB: "task_manager"

  backend:
    restart: always
    build:
      context: ./
      dockerfile: ./apps/backend/Dockerfile
    environment:
      PORT: "3005"
      DATABASE_URL: "postgres://task_user:task_password@postgres/task_manager?schema=public"
    ports:
      - 3005:3005
    depends_on:
      - postgres

  frontend:
    restart: always
    build:
      context: ./
      dockerfile: ./apps/frontend/Dockerfile
    environment:
      VITE_API_URL: "http://backend:3005"
    ports:
      - 3006:8080
    depends_on:
      - backend
